version: '3'


services:
  api:
    image: "${IMAGE}"
    command: python -m pet_feeding.api
    environment:
      PASSWORD: "pet"
      USER: "pet"
      DB: "pet"
      HOST: "db"
    ports:
      - 8080:80
    depends_on:
      - db

  admin-api:
    image: "${IMAGE}"
    command: python -m pet_feeding.admin_api
    environment:
      PASSWORD: "pet"
      USER: "pet"
      DB: "pet"
      HOST: "db"
    ports:
      - 8081:81
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      LC_ALL: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
      POSTGRES_PASSWORD: "pet"
      POSTGRES_USER: "pet"
      POSTGRES_DB: "pet"
      PGDATA: "/var/lib/postgresql/data/db/"
    ports:
      - 5432:5432


volumes:
  db:
